### PR TITLE
Add full state to the constructor

### PR DESCRIPTION
**Pull request by aarhus**
Unable to access the blockConcurrencyWhile through the proxy

### CODE REVIEW

**Comment by kwhitley** [comment]
Totally get this, but don't love the code smell if we implement it... `this.state.state`. Let's see if we can extend the native state, rather than appending it back into an alternative version of itself.

Example:
```js
this.state = state // from constructor

Object.assign(this.state, {
  ...otherStuff,
})
```

**Comment by aarhus** [comment]
Just tested this and it works well - I have added a "block" function to wrap to go with the easier interfaces that you have implemented.

**Comment by kschniedergers** [comment]
Any progress on this? I'd love to have access to the state so I can use the websocket hibernation api

**Comment by kwhitley** [comment]
My bad on the delay of this... I'll get this one out ASAP

**Pull request merged**
